export const sentinelaDetail = {
  badge: "1. Agente Sentinela",
  titleLead: "Monitoramento:",
  titleAccent: "O Impacto Real",
  metrics: [
    {
      value: "07min",
      label: "Tempo de reação (−94%)",
    },
    {
      value: "+18%",
      label: "Share of voice no tema",
    },
  ],
  stories: [
    {
      title: "O Desafio do Mandato",
      body: "A pauta nasce, viraliza e morre em poucas horas — e quem chega primeiro dita a narrativa. Sem monitoramento dedicado, o gabinete descobre o assunto pelo grupo de WhatsApp, já tarde demais para pautar o debate.",
    },
    {
      title: "A Ativação da IA",
      body: "O Agente Sentinela vigia 24h os portais, perfis de autoridades e redes que moldam a conversa do seu mandato. No instante em que uma pauta relevante surge, o alerta chega direto ao gabinete — pronto para virar conteúdo.",
    },
  ],
  console: {
    title: "Console Live — pautas mapeadas",
    subtitle: "Painel interativo com as pautas de maior potencial para gerar conteúdo do candidato.",
    columns: [
      "Tema selecionado",
      "Pauta identificada",
      "Link do post",
      "Score",
      "Curtidas",
      "Comentários",
      "Compart.",
      "Gerar Pauta com:",
    ] as const,
    rows: [
      {
        theme: "Direito Trabalhista",
        themeTone: "purple" as const,
        topic: "trabalhamos em média 48h/semana",
        network: "instagram" as const,
        handle: "@getulio_23",
        score: "↑300%",
        likes: "790",
        comments: "306",
        shares: "420",
        action: "Gêmeo Digital",
      },
      {
        theme: "Segurança Pública",
        themeTone: "blue" as const,
        topic: "aumento de furtos no centro",
        network: "instagram" as const,
        handle: "@brasil_26",
        score: "↑218%",
        likes: "1.2k",
        comments: "542",
        shares: "389",
        action: "Avatar Caricato",
      },
      {
        theme: "Saúde",
        themeTone: "purple" as const,
        topic: "falta de médicos nos postos",
        network: "tiktok" as const,
        handle: "@saude_br",
        score: "↑180%",
        likes: "3.4k",
        comments: "890",
        shares: "612",
        action: "Avatar 3D",
      },
    ],
    newPautaLabel: "Gerar pauta independente com:",
    formatOptions: ["Gêmeo Digital", "Avatar Caricato", "Avatar 3D"] as const,
    generateLabel: "Gerar Conteúdo",
  },
} as const;
